[package]
name = "rocks"
version = "0.0.1"
authors = ["BH1XUW <bh1xuw@gmail.com>"]
description = "RocksDB bindings for Rust."
repository = "https://github.com/bh1xuw/rust-rocks"
keywords = ["ffi", "rocksdb", "facebook", "database"]
categories = ["external-ffi-bindings", "database"]
license = "Apache-2.0"

include = [
    "**/*.rs",
    "**/*.h",
    "**/*.cc",
    "**/*.hpp",
    "Cargo.toml",
]

[dependencies]
rocks-sys = { path = "rocks-sys", version = "0.0.1" }

[dev-dependencies]
tempdir = "0.3"
